// TODO: does this need to be updated? how can we auto-generate this
const KNOWN_KEYWORDS = new Set<string>([
  // evergreen
  "Deathtouch",
  "Defender",
  "Double Strike",
  "Enchant",
  "Equip",
  "First Strike",
  "Flash",
  "Flying",
  "Haste",
  "Hexproof",
  "Indestructible",
  "Lifelink",
  "Menace",
  "Prowess",
  "Reach",
  "Trample",
  "Vigilance",
  // other
  "Absorb",
  "Affinity",
  "Amplify",
  "Annihilator",
  "Aura Swap",
  "Awaken",
  "Banding",
  "Battle Cry",
  "Bestow",
  "Bloodthirst",
  "Bushido",
  "Buyback",
  "Cascade",
  "Champion",
  "Changeling",
  "Cipher",
  "Conspire",
  "Convoke",
  "Cumulative Upkeep",
  "Cycling",
  "Dash",
  "Delve",
  "Dethrone",
  "Devoid",
  "Devour",
  "Dredge",
  "Echo",
  "Entwine",
  "Epic",
  "Evoke",
  "Evolve",
  "Exalted",
  "Exploit",
  "Explore",
  "Extort",
  "Fading",
  "Fear",
  "Flanking",
  "Flashback",
  "Forecast",
  "Fortify",
  "Frenzy",
  "Fuse",
  "Graft",
  "Gravestorm",
  "Haunt",
  "Hidden Agenda",
  "Hideaway",
  "Horsemanship",
  "Infect",
  "Ingest",
  "Intimidate",
  "Kicker",
  "Landhome",
  "Landwalk",
  "Level Up",
  "Living Weapon",
  "Madness",
  "Megamorph",
  "Miracle",
  "Modular",
  "Morph",
  "Myriad",
  "Ninjutsu",
  "Offering",
  "Outlast",
  "Overload",
  "Persist",
  "Phasing",
  "Poisonous",
  "Protection",
  "Provoke",
  "Prowl",
  "Rampage",
  "Rebound",
  "Recover",
  "Reinforce",
  "Renown",
  "Replicate",
  "Retrace",
  "Ripple",
  "Scavenge",
  "Skulk",
  "Shadow",
  "Shroud",
  "Soulbond",
  "Soulshift",
  "Splice",
  "Split Second",
  "Storm",
  "Substance",
  "Sunburst",
  "Surge",
  "Suspend",
  "Totem Armor",
  "Transfigure",
  "Tribute",
  "Undying",
  "Unearth",
  "Unleash",
  "Vanishing",
  "Wither",
]);

export function filterKeywords(keywords: string[] | undefined): string[] {
  if (!keywords || keywords.length === 0) return [];
  return keywords.filter((k) => KNOWN_KEYWORDS.has(k));
}
